import { DM_Serif_Display } from 'next/font/google';

export const dmSerif = DM_Serif_Display({
  weight: '400',
  subsets: ['latin'],
});

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  };
   
export default function RootLayout({ children }) {
    return (
      <html lang="en" className={dmSerif.className}>
        <body>{children}</body>
      </html>
    );
  }